version: '3.8'
services:
  frontend:
    build:
      context: ./frontend  # Set the context to the frontend directory
      dockerfile: Dockerfile-frontend  # Specify the Dockerfile name
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  # Set the context to the backend directory
      dockerfile: Dockerfile-backend  # Specify the Dockerfile name
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:admin@db:5432/backend
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
